

// ===== File: all_code_combined.ts =====



// ===== File: app\api\chat\route.ts =====

import { NextRequest, NextResponse } from "next/server";
import { queryDocuments } from "@/lib/langchain/vectorStore";
import { llm } from "@/lib/langchain/llm";

export async function POST(req: NextRequest) {
  try {
    const { question, video_id } = await req.json();

    if (!question) {
      return NextResponse.json(
        { success: false, error: "Question is required" },
        { status: 400 }
      );
    }

    const matches = await queryDocuments(question, video_id);

    const context = matches
      .map((m: any) => m.metadata?.text)
      .join("\n");

    const prompt = `
Answer the question based on context:

${context}

Question: ${question}
`;

    const response = await llm.invoke(prompt);

    return NextResponse.json({
      answer: response.content,
      sources: matches.map((m: any) => m.metadata?.source),
    });

  } catch (error: any) {
    console.error("CHAT ERROR:", error);

    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}

// ===== File: app\api\ingest\route.ts =====

import { NextRequest, NextResponse } from "next/server";
import { getTranscript } from "@/lib/youtube";
import { RecursiveCharacterTextSplitter } from "@langchain/textsplitters";
import { upsertDocuments } from "@/lib/langchain/vectorStore";

export async function POST(req: NextRequest) {
  try {
    const { video_id } = await req.json();

    if (!video_id) {
      return NextResponse.json(
        { success: false, error: "video_id is required" },
        { status: 400 }
      );
    }

    const transcript = await getTranscript(video_id);
    console.log(transcript);
    


    if (!transcript) {
      return NextResponse.json(
        { success: false, error: "Transcript not found" },
        { status: 404 }
      );
    }

    
    if (!transcript || transcript.trim().length < 20) {
  return NextResponse.json(
    { success: false, error: "Transcript is empty or too short" },
    { status: 400 }
  );
}

    const splitter = new RecursiveCharacterTextSplitter({
      chunkSize: 500,
      chunkOverlap: 50,
    });

    const docs = await splitter.createDocuments(
      [transcript],
      [
        {
          source: `https://youtube.com/watch?v=${video_id}`,
          video_id,
        },
      ]
    );

    await upsertDocuments(docs, video_id);

    return NextResponse.json({
      success: true,
      message: "Video ingested successfully",
    });

  } catch (error: any) {
    console.error("INGEST ERROR:", error);

    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}

// ===== File: app\api\notes\route.ts =====



// ===== File: app\api\ppt\route.ts =====



// ===== File: app\layout.tsx =====

// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ClientToaster from "@/components/ClientToaster"; 
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "YT-RAG-CHATBOT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Toaster/>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// ===== File: app\page.tsx =====

import ChatBox from "@/components/ChatBox";
import Navbar from "@/components/Navbar";
import VideoInput from "@/components/VideoInput";

export default function Home() {
  return (
    // Replaced harsh conic with a subtle dark theme depth
    <div className="min-h-screen bg-[#0a0a0a] text-white selection:bg-blue-500/30">
      <main className="max-w-4xl mx-auto px-6 py-12 space-y-10">
        <header className="text-center space-y-2">
          <h1 className="text-4xl font-bold bg-gradient-to-b from-white to-gray-400 bg-clip-text text-transparent">
            Video Intelligence
          </h1>
          <p className="text-gray-400">Ingest YouTube content and chat with the transcript instantly.</p>
        </header>
        
        <div className="bg-gray-900/50 border border-white/10 rounded-3xl p-1 backdrop-blur-sm shadow-2xl">
          <div className="bg-[#0f0f0f] rounded-[22px] p-6 lg:p-8">
            <VideoInput />
            <div className="my-8 border-t border-white/5" />
            <ChatBox />
          </div>
        </div>
      </main>
    </div>
  );
}

// ===== File: app\services\api.ts =====

import axios from "axios";

// Since backend is inside Next.js, no need for external base URL

export const ingestVideo = async (video_id: string) => {
  const res = await axios.post("/api/ingest", { video_id });
  return res.data;
};

export const chatWithAI = async (session_id: string, question: string) => {
  const res = await axios.post("/api/chat", { session_id, question });
  return res.data;
};

export const generateNotes = async (video_id: string) => {
  const res = await axios.post("/api/generate-notes", { video_id }, {
    responseType: "blob",
  });
  return res.data;
};

export const generatePPT = async (video_id: string) => {
  const res = await axios.post("/api/generate-ppt", { video_id }, {
    responseType: "blob",
  });
  return res.data;
};

// ===== File: lib\chroma.ts =====

"use server";
import { Chroma } from "@langchain/community/vectorstores/chroma";
import { MistralAIEmbeddings } from "@langchain/mistralai";

const embeddings = new MistralAIEmbeddings({
  model: "mistral-embed",
});

export const vectorStore = new Chroma(embeddings, {
  collectionName: "youtube-rag",
  url: "http://localhost:8000",
});

// ===== File: lib\langchain\embeddings.ts =====

import { MistralAIEmbeddings } from "@langchain/mistralai";

export const embeddings = new MistralAIEmbeddings({
  model: "mistral-embed",
  apiKey: process.env.MISTRAL_API_KEY, // ✅ REQUIRED
});

// ===== File: lib\langchain\llm.ts =====

import { ChatMistralAI } from "@langchain/mistralai"

export const llm = new ChatMistralAI({
    model: "mistral-small-latest",
    temperature: 0,
    maxRetries: 2,
});


// ===== File: lib\langchain\rag.ts =====



// ===== File: lib\langchain\retriever.ts =====



// ===== File: lib\langchain\vectorStore.ts =====

"use server"
import { vectorStore } from "../chroma";

export const upsertDocuments = async (docs: any[], video_id: string) => {
  if (!docs.length) throw new Error("No docs");

  console.log("Docs received:", docs.length);

  const formattedDocs = docs.map((doc) => ({
    pageContent: doc.pageContent,
    metadata: {
      ...doc.metadata,
      video_id,
    },
  }));

  // ✅ embeddings handled automatically
  await vectorStore.addDocuments(formattedDocs);

  console.log("✅ Stored in Chroma");
};

// ===== File: lib\utils.ts =====



// ===== File: lib\youtube.ts =====

import axios from "axios";
import { fetchTranscript } from "youtube-transcript-plus";

const sleep = (ms: number) => new Promise((res) => setTimeout(res, ms));

export const getTranscript = async (videoId: string) => {
  // 🟢 1. Primary Method (fast)
  try {
    const data = await fetchTranscript(videoId, { lang: "en" });

    return data.map((item: any) => item.text).join(" ");
  } catch (err: any) {
    console.warn("Primary transcript failed:", err.message);
  }

  // 🟡 2. Retry with delay (rate limit bypass)
  try {
    await sleep(2000);

    const data = await fetchTranscript(videoId, { lang: "en" });

    return data.map((item: any) => item.text).join(" ");
  } catch (err: any) {
    console.warn("Retry failed:", err.message);
  }

  // 🔵 3. Fallback API (backup)
  try {
    const res = await axios.get(
      `https://yt-transcript-api.vercel.app/api?videoId=${videoId}`
    );

    return res.data.transcript
      .map((item: any) => item.text)
      .join(" ");
  } catch (err: any) {
    console.error("Fallback API failed:", err.message);
  }

  // 🔴 Final failure
  throw new Error("All transcript methods failed");
};

// ===== File: next.config.ts =====

import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
};

export default nextConfig;


// ===== File: app\api\chat\route.ts =====

import { NextRequest, NextResponse } from "next/server";
import { queryDocuments } from "@/lib/langchain/vectorStore";
import { llm } from "@/lib/langchain/llm";

export async function POST(req: NextRequest) {
  try {
    const { question, video_id } = await req.json();

    if (!question) {
      return NextResponse.json(
        { success: false, error: "Question is required" },
        { status: 400 }
      );
    }

    const matches = await queryDocuments(question, video_id);

    const context = matches
      .map((m: any) => m.pageContent)
      .join("\n\n");

    // ✅ MUCH BETTER PROMPT
    const prompt = `
You are a helpful AI assistant.

Answer ONLY from the provided context.
If answer is not in context, say "I don't know".

Context:
${context}

Question: ${question}

Answer:
`;

    const response = await llm.invoke(prompt);

    return NextResponse.json({
      answer: response.content,
      sources: matches.map((m: any) => m.metadata?.source),
    });

  } catch (error: any) {
    console.error("CHAT ERROR:", error);

    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}

// ===== File: app\api\ingest\route.ts =====

import { NextRequest, NextResponse } from "next/server";
import { getTranscript } from "@/lib/youtube";
import { RecursiveCharacterTextSplitter } from "@langchain/textsplitters";
import { upsertDocuments } from "@/lib/langchain/vectorStore";

export async function POST(req: NextRequest) {
  try {
    const { video_id } = await req.json();

    if (!video_id) {
      return NextResponse.json(
        { success: false, error: "video_id is required" },
        { status: 400 }
      );
    }

    const transcript = await getTranscript(video_id);
    console.log(transcript);
    


    if (!transcript) {
      return NextResponse.json(
        { success: false, error: "Transcript not found" },
        { status: 404 }
      );
    }

    
    if (!transcript || transcript.trim().length < 20) {
  return NextResponse.json(
    { success: false, error: "Transcript is empty or too short" },
    { status: 400 }
  );
}

    const splitter = new RecursiveCharacterTextSplitter({
      chunkSize: 500,
      chunkOverlap: 50,
    });

    const docs = await splitter.createDocuments(
      [transcript],
      [
        {
          source: `https://youtube.com/watch?v=${video_id}`,
          video_id,
        },
      ]
    );

    await upsertDocuments(docs, video_id);

    return NextResponse.json({
      success: true,
      message: "Video ingested successfully",
    });

  } catch (error: any) {
    console.error("INGEST ERROR:", error);

    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}

// ===== File: app\api\notes\route.ts =====



// ===== File: app\api\ppt\route.ts =====



// ===== File: app\layout.tsx =====

// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ClientToaster from "@/components/ClientToaster"; 
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "YT-RAG-CHATBOT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Toaster/>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// ===== File: app\page.tsx =====

import ChatBox from "@/components/ChatBox";
import Navbar from "@/components/Navbar";
import VideoInput from "@/components/VideoInput";

export default function Home() {
  return (
    // Replaced harsh conic with a subtle dark theme depth
    <div className="min-h-screen bg-[#0a0a0a] text-white selection:bg-blue-500/30">
      <main className="max-w-4xl mx-auto px-6 py-12 space-y-10">
        <header className="text-center space-y-2">
          <h1 className="text-4xl font-bold bg-gradient-to-b from-white to-gray-400 bg-clip-text text-transparent">
            Video Intelligence
          </h1>
          <p className="text-gray-400">Ingest YouTube content and chat with the transcript instantly.</p>
        </header>
        
        <div className="bg-gray-900/50 border border-white/10 rounded-3xl p-1 backdrop-blur-sm shadow-2xl">
          <div className="bg-[#0f0f0f] rounded-[22px] p-6 lg:p-8">
            <VideoInput />
            <div className="my-8 border-t border-white/5" />
            <ChatBox />
          </div>
        </div>
      </main>
    </div>
  );
}

// ===== File: app\services\api.ts =====

import axios from "axios";

// Since backend is inside Next.js, no need for external base URL

export const ingestVideo = async (video_id: string) => {
  const res = await axios.post("/api/ingest", { video_id });
  return res.data;
};

export const chatWithAI = async (video_id: string, question: string) => {
  const res = await axios.post("/api/chat", { video_id, question });
  return res.data;
};

export const generateNotes = async (video_id: string) => {
  const res = await axios.post("/api/generate-notes", { video_id }, {
    responseType: "blob",
  });
  return res.data;
};

export const generatePPT = async (video_id: string) => {
  const res = await axios.post("/api/generate-ppt", { video_id }, {
    responseType: "blob",
  });
  return res.data;
};

// ===== File: lib\chroma.ts =====

// lib/chroma.ts

import { Chroma } from "@langchain/community/vectorstores/chroma";
import { MistralAIEmbeddings } from "@langchain/mistralai";

export const vectorStore = await Chroma.fromExistingCollection(
  new MistralAIEmbeddings(),
  {
    collectionName: "yt-rag-llm",

    url: "https://api.trychroma.com", // ✅ IMPORTANT

    collectionMetadata: {},

    // 👇 THIS IS THE REAL FIX
    clientParams: {
      headers: {
        "x-chroma-token": process.env.CHROMA_API_KEY!,
      },
      tenant: process.env.CHROMA_TENANT!,
      database: process.env.CHROMA_DATABASE!,
    },
  }
);
import { CloudClient } from "chromadb";

const client = new CloudClient({
  apiKey: process.env.CHROMA_API_KEY,
  tenant: process.env.CHROMA_TENANT,
  database: process.env.CHROMA_DATABASE
});

// ===== File: lib\initChroma.ts =====

import { ChromaClient } from "chromadb";

export const initChroma = async () => {
  try {
    const client = new ChromaClient({
      host: "api.trychroma.com",
      port: 443,
      ssl: true,
      headers: {
        "x-chroma-token": process.env.CHROMA_API_KEY!,
      },
      tenant: process.env.CHROMA_TENANT!,
      database: process.env.CHROMA_DATABASE!,
    });

    const collection = await client.getCollection({
      name: "yt-rag-llm",
    });

    console.log("✅ Connected to collection:", collection.name);

    return collection;

  } catch (error) {
    console.error("❌ Chroma ERROR:", error);
    throw error;
  }
};

// ===== File: lib\langchain\embeddings.ts =====

// lib/langchain/embeddings.ts

import { MistralAIEmbeddings } from "@langchain/mistralai";

export const embeddings = new MistralAIEmbeddings({
  model: "mistral-embed",
  apiKey: process.env.MISTRAL_API_KEY,
});

// ===== File: lib\langchain\llm.ts =====

import { ChatMistralAI } from "@langchain/mistralai"

export const llm = new ChatMistralAI({
    model: "mistral-small-latest",
    temperature: 0,
    maxRetries: 2,
});


// ===== File: lib\langchain\rag.ts =====



// ===== File: lib\langchain\retriever.ts =====



// ===== File: lib\langchain\vectorStore.ts =====

// lib/langchain/vectorStore.ts

import { vectorStore } from "../chroma";


export const upsertDocuments = async (docs: any[], video_id: string) => {
  if (!docs.length) throw new Error("No docs");

  console.log("Docs received:", docs.length);

  const formattedDocs = docs.map((doc) => ({
    pageContent: doc.pageContent,
    metadata: {
      ...doc.metadata,
      video_id,
    },
  }));

  await vectorStore.addDocuments(formattedDocs);

  console.log("✅ Stored in Chroma");
};

export const queryDocuments = async (query: string, video_id: string) => {
  const results = await vectorStore.similaritySearch(query, 5, {
    video_id, // ✅ filter by video
  });

  return results;
};


// ===== File: lib\utils.ts =====



// ===== File: lib\youtube.ts =====

import axios from "axios";
import { fetchTranscript } from "youtube-transcript-plus";

const sleep = (ms: number) => new Promise((res) => setTimeout(res, ms));

export const getTranscript = async (videoId: string) => {
  // 🟢 1. Primary Method (fast)
  try {
    const data = await fetchTranscript(videoId, { lang: "en" });

    return data.map((item: any) => item.text).join(" ");
  } catch (err: any) {
    console.warn("Primary transcript failed:", err.message);
  }

  // 🟡 2. Retry with delay (rate limit bypass)
  try {
    await sleep(2000);

    const data = await fetchTranscript(videoId, { lang: "en" });

    return data.map((item: any) => item.text).join(" ");
  } catch (err: any) {
    console.warn("Retry failed:", err.message);
  }

  // 🔵 3. Fallback API (backup)
  try {
    const res = await axios.get(
      `https://yt-transcript-api.vercel.app/api?videoId=${videoId}`
    );

    return res.data.transcript
      .map((item: any) => item.text)
      .join(" ");
  } catch (err: any) {
    console.error("Fallback API failed:", err.message);
  }

  // 🔴 Final failure
  throw new Error("All transcript methods failed");
};

// ===== File: next.config.ts =====

import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  experimental: {
    serverComponentsExternalPackages: ["chromadb"],
  },
};

export default nextConfig;